# Generated by Django 3.2.8 on 2021-10-25 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20211022_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('kelas', models.CharField(choices=[('SHS10SOC', 'SHS10SOC'), ('SHS10SCI', 'SHS10SCI'), ('SHS11SOC', 'SHS11SOC'), ('SHS11SCI', 'SHS11SCI'), ('SHS12SOC', 'SHS12SOC'), ('SHS12SCI', 'SHS12SCI')], max_length=8)),
                ('voted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
