# Generated by Django 3.2.8 on 2021-10-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_student_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='kelas',
            field=models.PositiveSmallIntegerField(choices=[(8, 'SHS10SCI'), (9, 'SHS10SOC'), (10, 'SHS11SCI'), (11, 'SHS11SOC'), (12, 'SHS12SCI'), (13, 'SHS12SOC')]),
        ),
    ]
