# Generated by Django 3.2.8 on 2021-10-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='candidates')),
                ('name', models.CharField(max_length=100)),
                ('visi', models.TextField()),
                ('misi', models.TextField()),
            ],
        ),
    ]
