# Generated by Django 3.2.8 on 2021-10-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='total_vote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
