# Generated by Django 3.2.8 on 2021-10-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211022_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='ketua',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='wakil',
            field=models.CharField(max_length=100),
        ),
    ]
