# Generated by Django 3.2.8 on 2021-10-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211026_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['date_added']},
        ),
    ]
