# Generated by Django 3.2.8 on 2021-11-12 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_candidate_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 5, 58, 31, 175152, tzinfo=utc)),
        ),
    ]
